### ISSUE TITLE
Project 1 - Omega Server Compatability

### ISSUE THREAD

**Issue by lankm** [lankm/uta-dbms#3]
Required compatibility

The project must work on the UTA Omega Server. Requirement found on page 8 of project_description.pdf.

Occasionally check this issue and keep the project working on Omega throughout development.

> - All the codes will be evaluated on omega.uta.edu – the University’s UNIX server. Check the following link for more information. 
> https://uta.service-now.com/kb_view.do?sysparm_article=KB0010329

**Comment by JanuarySystem** [comment]
Seems to work. Just got to make sure we package it correctly for them.

**Comment by JanuarySystem** [comment]
I am pretty confident that it works after some testing.

**Comment by JanuarySystem** [comment]
In order to maintain compatibility, any further changes should be purely cosmetic in the form of comment alterations if possible.
